# Generated by Django 2.2.1 on 2019-05-26 04:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flashr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pain',
            name='time_stamp',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
